### ISSUE TITLE
`unknown flag `msg`` error

### ISSUE THREAD

**Issue by bixu** [honeycombio/honeymarker#58]
Honeymarker called from the Docker Image on Hub fails for me.

**Versions**

- Docker Image ID: `085517e8a414`

```shell
docker run -it honeycombio/honeymarker:latest --version
Honeymarker version 0.2.8
```

**Steps to reproduce**

```shell
docker run -it honeycombio/honeymarker:latest --dataset=blake --writekey=<api_key> add --msg=<some_string> --type=<some_type> --url=<some_url>
           
unknown flag `msg'
```

**Additional context**

I've been using the tool to create post-deploy hooks in Helm. This started failing at some point after an update of the Hub image. Example hook:

```yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: "otel-pipeline-deployment-marker"
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/version: {{ .Chart.Version }}
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  backoffLimit: 2
  template:
    metadata:
      name: "{{ .Release.Name }}"
      labels:
        app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
        app.kubernetes.io/instance: {{ .Release.Name | quote }}
        helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    spec:
      restartPolicy: Never
      containers:
      - name: honeycomb-events-dataset-marker
        image: {{ .Values.honeycomb.honeymarker.image }}
        command: 
        - "honeymarker"
        - "add"
        - "--writekey={{ .Values.honeycomb.apiKey }}"
        - "--msg={{ .Chart.Name }}-{{ .Chart.Version }}"
        - "--type=deployment"
        - "--url=XXXXXX"
        - "--dataset={{ .Values.honeycomb.dataset }}"
```
